### ISSUE TITLE
how to add expansionTile() to items in sideMenu

### ISSUE THREAD

**Issue by usernamekk** [Jamalianpour/easy_sidemenu#23]

**Comment by Jamalianpour** [comment]
Hello,
Why there is no description???
I think you want expandable `sideMenuItem` but unfortunately it wasn't possible at this time.
Look forward for new versions.

**Comment by usernamekk** [comment]
Thanks Jamalianpour/easy_sidemenu
Looking forward for it

**Comment by AyberkAhmet** [comment]
First of all, thanks for this library. It's very well thought out and designed. Are you considering adding this feature( expandable tile like [https://api.flutter.dev/flutter/material/ExpansionTile-class.html](https://api.flutter.dev/flutter/material/ExpansionTile-class.html) )? I think the lack of this feature is a big shortcoming. Even with this feature, it can be used in any project without any problems.

**Comment by antoninobajeli** [comment]
I'm trying to add an expansion tile. I did a proposal in my pull request. I'm open to collaborating in order to realize a useful solution. #36 

<img width="683" alt="Screenshot 2022-11-27 at 12 04 31" src="https://user-images.githubusercontent.com/5979237/204131890-950ee140-362b-45a6-82cd-efcff68d102f.png">

**Comment by Jamalianpour** [comment]
Sorry but that code is not clean and easy to use
I did rollback and remove that from master branch, this is my bad because I don't review code before merge that PR

**Comment by AbhishekDvs** [comment]
Hey, when I'm trying to add an expansion tile similarly, it's throwing an error.
It's throwing "The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
black striped pattern. This is usually caused by the contents being too big for the RenderFlex."

How did you merge an expansion Tile with this menu? 

cc @antoninobajeli
