### ISSUE TITLE
Sidemenu blinking when resizing window

### ISSUE THREAD

**Issue by awpehl** [Jamalianpour/easy_sidemenu#74]
When you're resizing the window the sidemenu will change as well and starts resizing. The problem is that's starting to blink because of rebuilding the UI.

**Comment by aditya113141** [comment]
Hey, I made some PRs which should have solved this issue. You can clone package from [my fork](https://github.com/aditya113141/easy_sidemenu) and see if the issue still persists. Let me know if you face issue.                          If you installed the package from [here](https://pub.dev/packages/easy_sidemenu/), then the issue can occur because the published version is old and doesn't reflects the recent PRs.

**Comment by awpehl** [comment]
Will check asap and let you know!

**Comment by awpehl** [comment]
It seems I'm already using this version but blinking still happens :/

**Comment by aditya113141** [comment]
Fixed it in my fork. Please check and review. Will make a PR if it is perfect. My fork also contains implementation of submenu/Expandable tiles.

**Comment by Jamalianpour** [comment]
@aditya113141 why you don't open a pull request here?

**Comment by awpehl** [comment]
Seems to be working. At least it fixed this problem!
